# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{nom_nom}
  s.version = "0.0.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Nolan Eakins"]
  s.date = %q{2010-09-26}
  s.description = %q{I consume web service. Nom nom nom.}
  s.email = %q{sneakin+nomnom@semanticgap.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.md"
  ]
  s.files = [
    ".gitignore",
     "LICENSE",
     "README.md",
     "Rakefile",
     "VERSION",
     "examples/bitter.rb",
     "examples/syncd.rb",
     "lib/nom_nom.rb",
     "lib/nom_nom/resource.rb",
     "lib/nom_nom/service.rb",
     "nom_nom.gemspec",
     "spec/nom_nom_spec.rb",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/sneakin/nom-nom}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{COOKIE!!}
  s.test_files = [
    "spec/nom_nom_spec.rb",
     "spec/spec_helper.rb",
     "examples/bitter.rb",
     "examples/syncd.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_runtime_dependency(%q<nokogiri>, ["= 1.4.3.1"])
      s.add_runtime_dependency(%q<httparty>, ["= 0.6.1"])
      s.add_runtime_dependency(%q<activesupport>, ["= 3.0.0"])
    else
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<nokogiri>, ["= 1.4.3.1"])
      s.add_dependency(%q<httparty>, ["= 0.6.1"])
      s.add_dependency(%q<activesupport>, ["= 3.0.0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<nokogiri>, ["= 1.4.3.1"])
    s.add_dependency(%q<httparty>, ["= 0.6.1"])
    s.add_dependency(%q<activesupport>, ["= 3.0.0"])
  end
end

